version: '3.8'

services:
  # PostgreSQL database for testing
  postgres:
    image: postgres:15-alpine
    container_name: community-postgres-test
    environment:
      POSTGRES_DB: community_test_db
      POSTGRES_USER: community_test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U community_test_user -d community_test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis for testing
  redis:
    image: redis:7-alpine
    container_name: community-redis-test
    ports:
      - "6379:6379"
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:
  redis_test_data: 