version: '3.8'

services:
  # Development container service
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: dev-container
    volumes:
      # Mount the entire project directory
      - .:/workspace:cached
    working_dir: /workspace
    # Keep the container running for development
    command: sleep infinity

  # Solana local validator for testing
  solana-local-validator:
    image: solanalabs/solana:v1.17.20
    container_name: solana-local-validator
    ports:
      - "8899:8899" # RPC
      - "8900:8900" # Websocket
    command: solana-test-validator --no-bpf-strict
